
export const countries = {
  ru: [
    { id: "de", name: "Германия" },
    { id: "fr", name: "Франция" },
    { id: "it", name: "Италия" },
    { id: "es", name: "Испания" },
    { id: "nl", name: "Нидерланды" },
    { id: "be", name: "Бельгия" },
    { id: "pt", name: "Португалия" },
    { id: "at", name: "Австрия" },
    { id: "pl", name: "Польша" },
    { id: "dk", name: "Дания" },
    { id: "se", name: "Швеция" },
    { id: "fi", name: "Финляндия" },
  ],
  en: [
    { id: "de", name: "Germany" },
    { id: "fr", name: "France" },
    { id: "it", name: "Italy" },
    { id: "es", name: "Spain" },
    { id: "nl", name: "Netherlands" },
    { id: "be", name: "Belgium" },
    { id: "pt", name: "Portugal" },
    { id: "at", name: "Austria" },
    { id: "pl", name: "Poland" },
    { id: "dk", name: "Denmark" },
    { id: "se", name: "Sweden" },
    { id: "fi", name: "Finland" },
  ],
  es: [
    { id: "de", name: "Alemania" },
    { id: "fr", name: "Francia" },
    { id: "it", name: "Italia" },
    { id: "es", name: "España" },
    { id: "nl", name: "Países Bajos" },
    { id: "be", name: "Bélgica" },
    { id: "pt", name: "Portugal" },
    { id: "at", name: "Austria" },
    { id: "pl", name: "Polonia" },
    { id: "dk", name: "Dinamarca" },
    { id: "se", name: "Suecia" },
    { id: "fi", name: "Finlandia" },
  ],
};

export const cities = {
  ru: {
    de: [
      { id: "ber", name: "Берлин" },
      { id: "mun", name: "Мюнхен" },
      { id: "ham", name: "Гамбург" },
      { id: "fra", name: "Франкфурт" },
      { id: "col", name: "Кёльн" },
    ],
    fr: [
      { id: "par", name: "Париж" },
      { id: "lyo", name: "Лион" },
      { id: "mar", name: "Марсель" },
      { id: "bor", name: "Бордо" },
      { id: "tls", name: "Тулуза" },
    ],
    it: [
      { id: "rom", name: "Рим" },
      { id: "mil", name: "Милан" },
      { id: "nap", name: "Неаполь" },
      { id: "tur", name: "Турин" },
      { id: "flo", name: "Флоренция" },
    ],
    es: [
      { id: "mad", name: "Мадрид" },
      { id: "bcn", name: "Барселона" },
      { id: "val", name: "Валенсия" },
      { id: "sev", name: "Севилья" },
      { id: "bil", name: "Бильбао" },
    ],
    nl: [
      { id: "ams", name: "Амстердам" },
      { id: "rot", name: "Роттердам" },
      { id: "hag", name: "Гаага" },
      { id: "utr", name: "Утрехт" },
      { id: "ein", name: "Эйндховен" },
    ],
    be: [
      { id: "bru", name: "Брюссель" },
      { id: "ant", name: "Антверпен" },
      { id: "gnt", name: "Гент" },
      { id: "lie", name: "Льеж" },
    ],
    pt: [
      { id: "lis", name: "Лиссабон" },
      { id: "por", name: "Порту" },
      { id: "far", name: "Фару" },
    ],
    at: [
      { id: "vie", name: "Вена" },
      { id: "grz", name: "Грац" },
      { id: "lin", name: "Линц" },
    ],
    pl: [
      { id: "war", name: "Варшава" },
      { id: "kra", name: "Краков" },
      { id: "wro", name: "Вроцлав" },
    ],
    dk: [
      { id: "cop", name: "Копенгаген" },
      { id: "aar", name: "Орхус" },
      { id: "ode", name: "Оденсе" },
    ],
    se: [
      { id: "sto", name: "Стокгольм" },
      { id: "got", name: "Гётеборг" },
      { id: "mal", name: "Мальмё" },
    ],
    fi: [
      { id: "hel", name: "Хельсинки" },
      { id: "esp", name: "Эспоо" },
      { id: "tam", name: "Тампере" },
    ],
  },
  en: {
    de: [
      { id: "ber", name: "Berlin" },
      { id: "mun", name: "Munich" },
      { id: "ham", name: "Hamburg" },
      { id: "fra", name: "Frankfurt" },
      { id: "col", name: "Cologne" },
    ],
    fr: [
      { id: "par", name: "Paris" },
      { id: "lyo", name: "Lyon" },
      { id: "mar", name: "Marseille" },
      { id: "bor", name: "Bordeaux" },
      { id: "tls", name: "Toulouse" },
    ],
    it: [
      { id: "rom", name: "Rome" },
      { id: "mil", name: "Milan" },
      { id: "nap", name: "Naples" },
      { id: "tur", name: "Turin" },
      { id: "flo", name: "Florence" },
    ],
    es: [
      { id: "mad", name: "Madrid" },
      { id: "bcn", name: "Barcelona" },
      { id: "val", name: "Valencia" },
      { id: "sev", name: "Seville" },
      { id: "bil", name: "Bilbao" },
    ],
    nl: [
      { id: "ams", name: "Amsterdam" },
      { id: "rot", name: "Rotterdam" },
      { id: "hag", name: "The Hague" },
      { id: "utr", name: "Utrecht" },
      { id: "ein", name: "Eindhoven" },
    ],
    be: [
      { id: "bru", name: "Brussels" },
      { id: "ant", name: "Antwerp" },
      { id: "gnt", name: "Ghent" },
      { id: "lie", name: "Liege" },
    ],
    pt: [
      { id: "lis", name: "Lisbon" },
      { id: "por", name: "Porto" },
      { id: "far", name: "Faro" },
    ],
    at: [
      { id: "vie", name: "Vienna" },
      { id: "grz", name: "Graz" },
      { id: "lin", name: "Linz" },
    ],
    pl: [
      { id: "war", name: "Warsaw" },
      { id: "kra", name: "Krakow" },
      { id: "wro", name: "Wroclaw" },
    ],
    dk: [
      { id: "cop", name: "Copenhagen" },
      { id: "aar", name: "Aarhus" },
      { id: "ode", name: "Odense" },
    ],
    se: [
      { id: "sto", name: "Stockholm" },
      { id: "got", name: "Gothenburg" },
      { id: "mal", name: "Malmo" },
    ],
    fi: [
      { id: "hel", name: "Helsinki" },
      { id: "esp", name: "Espoo" },
      { id: "tam", name: "Tampere" },
    ],
  },
  es: {
    de: [
      { id: "ber", name: "Berlín" },
      { id: "mun", name: "Múnich" },
      { id: "ham", name: "Hamburgo" },
      { id: "fra", name: "Fráncfort" },
      { id: "col", name: "Colonia" },
    ],
    fr: [
      { id: "par", name: "París" },
      { id: "lyo", name: "Lyon" },
      { id: "mar", name: "Marsella" },
      { id: "bor", name: "Burdeos" },
      { id: "tls", name: "Toulouse" },
    ],
    it: [
      { id: "rom", name: "Roma" },
      { id: "mil", name: "Milán" },
      { id: "nap", name: "Nápoles" },
      { id: "tur", name: "Turín" },
      { id: "flo", name: "Florencia" },
    ],
    es: [
      { id: "mad", name: "Madrid" },
      { id: "bcn", name: "Barcelona" },
      { id: "val", name: "Valencia" },
      { id: "sev", name: "Sevilla" },
      { id: "bil", name: "Bilbao" },
    ],
    nl: [
      { id: "ams", name: "Ámsterdam" },
      { id: "rot", name: "Róterdam" },
      { id: "hag", name: "La Haya" },
      { id: "utr", name: "Utrecht" },
      { id: "ein", name: "Eindhoven" },
    ],
    be: [
      { id: "bru", name: "Bruselas" },
      { id: "ant", name: "Amberes" },
      { id: "gnt", name: "Gante" },
      { id: "lie", name: "Lieja" },
    ],
    pt: [
      { id: "lis", name: "Lisboa" },
      { id: "por", name: "Oporto" },
      { id: "far", name: "Faro" },
    ],
    at: [
      { id: "vie", name: "Viena" },
      { id: "grz", name: "Graz" },
      { id: "lin", name: "Linz" },
    ],
    pl: [
      { id: "war", name: "Varsovia" },
      { id: "kra", name: "Cracovia" },
      { id: "wro", name: "Breslavia" },
    ],
    dk: [
      { id: "cop", name: "Copenhague" },
      { id: "aar", name: "Aarhus" },
      { id: "ode", name: "Odense" },
    ],
    se: [
      { id: "sto", name: "Estocolmo" },
      { id: "got", name: "Gotemburgo" },
      { id: "mal", name: "Malmö" },
    ],
    fi: [
      { id: "hel", name: "Helsinki" },
      { id: "esp", name: "Espoo" },
      { id: "tam", name: "Tampere" },
    ],
  },
};
