
import { CountriesByLang } from './types';

export const countries: CountriesByLang = {
  ru: [
    { id: "de", name: "Германия" },
    { id: "fr", name: "Франция" },
    { id: "it", name: "Италия" },
    { id: "es", name: "Испания" },
    { id: "nl", name: "Нидерланды" },
    { id: "be", name: "Бельгия" },
    { id: "pt", name: "Португалия" },
    { id: "at", name: "Австрия" },
    { id: "pl", name: "Польша" },
    { id: "dk", name: "Дания" },
    { id: "se", name: "Швеция" },
    { id: "fi", name: "Финляндия" },
    { id: "ie", name: "Ирландия" },
    { id: "gr", name: "Греция" },
    { id: "cz", name: "Чехия" },
    { id: "hu", name: "Венгрия" },
    { id: "ro", name: "Румыния" },
    { id: "bg", name: "Болгария" },
    { id: "hr", name: "Хорватия" },
    { id: "sk", name: "Словакия" }
  ],
  en: [
    { id: "de", name: "Germany" },
    { id: "fr", name: "France" },
    { id: "it", name: "Italy" },
    { id: "es", name: "Spain" },
    { id: "nl", name: "Netherlands" },
    { id: "be", name: "Belgium" },
    { id: "pt", name: "Portugal" },
    { id: "at", name: "Austria" },
    { id: "pl", name: "Poland" },
    { id: "dk", name: "Denmark" },
    { id: "se", name: "Sweden" },
    { id: "fi", name: "Finland" },
    { id: "ie", name: "Ireland" },
    { id: "gr", name: "Greece" },
    { id: "cz", name: "Czech Republic" },
    { id: "hu", name: "Hungary" },
    { id: "ro", name: "Romania" },
    { id: "bg", name: "Bulgaria" },
    { id: "hr", name: "Croatia" },
    { id: "sk", name: "Slovakia" }
  ],
  es: [
    { id: "de", name: "Alemania" },
    { id: "fr", name: "Francia" },
    { id: "it", name: "Italia" },
    { id: "es", name: "España" },
    { id: "nl", name: "Países Bajos" },
    { id: "be", name: "Bélgica" },
    { id: "pt", name: "Portugal" },
    { id: "at", name: "Austria" },
    { id: "pl", name: "Polonia" },
    { id: "dk", name: "Dinamarca" },
    { id: "se", name: "Suecia" },
    { id: "fi", name: "Finlandia" },
    { id: "ie", name: "Irlanda" },
    { id: "gr", name: "Grecia" },
    { id: "cz", name: "República Checa" },
    { id: "hu", name: "Hungría" },
    { id: "ro", name: "Rumanía" },
    { id: "bg", name: "Bulgaria" },
    { id: "hr", name: "Croacia" },
    { id: "sk", name: "Eslovaquia" }
  ]
};
