
import { CitiesByLang } from '../types';

export const easternEuropeCities: CitiesByLang = {
  ru: {
    bg: [
      { id: "burg", name: "Бургас" },
      { id: "var", name: "Варна" },
      { id: "vel", name: "Велико-Тырново" },
      { id: "vid", name: "Видин" },
      { id: "vrа", name: "Враца" },
      { id: "gab", name: "Габрово" },
      { id: "dob", name: "Добрич" },
      { id: "kar", name: "Карлово" },
      { id: "kaz", name: "Казанлык" },
      { id: "kyr", name: "Кырджали" },
      { id: "kus", name: "Кюстендил" },
      { id: "lov", name: "Ловеч" },
      { id: "mon", name: "Монтана" },
      { id: "paz", name: "Пазарджик" },
      { id: "per", name: "Перник" },
      { id: "ple", name: "Плевен" },
      { id: "plo", name: "Пловдив" },
      { id: "raz", name: "Разград" },
      { id: "rou", name: "Русе" },
      { id: "sil", name: "Силистра" },
      { id: "sli", name: "Сливен" },
      { id: "smo", name: "Смолян" },
      { id: "sof", name: "София" },
      { id: "sta", name: "Стара-Загора" },
      { id: "tar", name: "Тырговиште" }
    ],
    hr: [
      { id: "bjel", name: "Бьеловар" },
      { id: "var", name: "Вараждин" },
      { id: "vin", name: "Винковци" },
      { id: "vuk", name: "Вуковар" },
      { id: "dub", name: "Дубровник" },
      { id: "zad", name: "Задар" },
      { id: "zag", name: "Загреб" },
      { id: "kar", name: "Карловац" },
      { id: "kop", name: "Копривница" },
      { id: "kra", name: "Крапина" },
      { id: "mak", name: "Макарска" },
      { id: "osi", name: "Осиек" },
      { id: "paz", name: "Пазин" },
      { id: "poz", name: "Пожега" },
      { id: "pul", name: "Пула" },
      { id: "rij", name: "Риека" },
      { id: "sis", name: "Сисак" },
      { id: "spl", name: "Сплит" },
      { id: "shi", name: "Шибеник" },
      { id: "sla", name: "Славонски-Брод" },
      { id: "tro", name: "Трогир" },
      { id: "vir", name: "Вировитица" }
    ],
    sk: [
      { id: "ban", name: "Банска-Бистрица" },
      { id: "bra", name: "Братислава" },
      { id: "gal", name: "Галанта" },
      { id: "gel", name: "Гелница" },
      { id: "dol", name: "Дольны-Кубин" },
      { id: "zil", name: "Жилина" },
      { id: "zvo", name: "Зволен" },
      { id: "kom", name: "Комарно" },
      { id: "kos", name: "Кошице" },
      { id: "lev", name: "Левице" },
      { id: "lip", name: "Липтовски-Микулаш" },
      { id: "luc", name: "Лученец" },
      { id: "mar", name: "Мартин" },
      { id: "mic", name: "Михаловце" },
      { id: "nit", name: "Нитра" },
      { id: "nov", name: "Нове-Замки" },
      { id: "pop", name: "Попрад" },
      { id: "pre", name: "Прешов" },
      { id: "pri", name: "Приевидза" },
      { id: "roz", name: "Рожнява" },
      { id: "tre", name: "Тренчин" },
      { id: "trn", name: "Трнава" }
    ],
    ro: [
      { id: "ara", name: "Арад" },
      { id: "bac", name: "Бакэу" },
      { id: "bra", name: "Брашов" },
      { id: "buc", name: "Бухарест" },
      { id: "gal", name: "Галац" },
      { id: "dec", name: "Дева" },
      { id: "ias", name: "Яссы" },
      { id: "clu", name: "Клуж-Напока" },
      { id: "con", name: "Констанца" },
      { id: "cra", name: "Крайова" },
      { id: "mag", name: "Мангалия" },
      { id: "med", name: "Медиаш" },
      { id: "ora", name: "Орадя" },
      { id: "pit", name: "Питешти" },
      { id: "plo", name: "Плоешти" },
      { id: "rim", name: "Рымнику-Вылча" },
      { id: "sib", name: "Сибиу" },
      { id: "suc", name: "Сучава" },
      { id: "tim", name: "Тимишоара" },
      { id: "tir", name: "Тыргу-Муреш" },
      { id: "foc", name: "Фокшани" },
      { id: "hun", name: "Хунедоара" }
    ],
    hu: [
      { id: "bek", name: "Бекешчаба" },
      { id: "bud", name: "Будапешт" },
      { id: "vec", name: "Вац" },
      { id: "ves", name: "Веспрем" },
      { id: "deb", name: "Дебрецен" },
      { id: "dun", name: "Дунауйварош" },
      { id: "kad", name: "Капошвар" },
      { id: "kec", name: "Кечкемет" },
      { id: "mis", name: "Мишкольц" },
      { id: "nad", name: "Надьканижа" },
      { id: "nic", name: "Ниредьхаза" },
      { id: "paz", name: "Пакш" },
      { id: "pec", name: "Печ" },
      { id: "sag", name: "Шагвар" },
      { id: "sal", name: "Шальготарьян" },
      { id: "seg", name: "Сегед" },
      { id: "sek", name: "Секешфехервар" },
      { id: "sol", name: "Сольнок" },
      { id: "som", name: "Сомбатхей" },
      { id: "sop", name: "Шопрон" },
      { id: "tat", name: "Татабанья" },
      { id: "zal", name: "Залаэгерсег" }
    ],
    cz: [
      { id: "brn", name: "Брно" },
      { id: "dec", name: "Дечин" },
      { id: "zli", name: "Злин" },
      { id: "jih", name: "Йиглава" },
      { id: "kar", name: "Карловы Вары" },
      { id: "kla", name: "Кладно" },
      { id: "kol", name: "Колин" },
      { id: "lib", name: "Либерец" },
      { id: "lit", name: "Литомержице" },
      { id: "mol", name: "Млада-Болеслав" },
      { id: "mos", name: "Мост" },
      { id: "olo", name: "Оломоуц" },
      { id: "opa", name: "Опава" },
      { id: "ost", name: "Острава" },
      { id: "par", name: "Пардубице" },
      { id: "pil", name: "Пльзень" },
      { id: "pra", name: "Прага" },
      { id: "pro", name: "Простеёв" },
      { id: "tab", name: "Табор" },
      { id: "tep", name: "Теплице" },
      { id: "ust", name: "Усти-над-Лабем" },
      { id: "hra", name: "Градец-Кралове" }
    ]
  },
  en: {
    bg: [
      { id: "burg", name: "Burgas" },
      { id: "var", name: "Varna" },
      { id: "vel", name: "Veliko Tarnovo" },
      { id: "vid", name: "Vidin" },
      { id: "vrа", name: "Vratsa" },
      { id: "gab", name: "Gabrovo" },
      { id: "dob", name: "Dobrich" },
      { id: "kar", name: "Karlovo" },
      { id: "kaz", name: "Kazanlak" },
      { id: "kyr", name: "Kardzhali" },
      { id: "kus", name: "Kyustendil" },
      { id: "lov", name: "Lovech" },
      { id: "mon", name: "Montana" },
      { id: "paz", name: "Pazardzhik" },
      { id: "per", name: "Pernik" },
      { id: "ple", name: "Pleven" },
      { id: "plo", name: "Plovdiv" },
      { id: "raz", name: "Razgrad" },
      { id: "rou", name: "Ruse" },
      { id: "sil", name: "Silistra" },
      { id: "sli", name: "Sliven" },
      { id: "smo", name: "Smolyan" },
      { id: "sof", name: "Sofia" },
      { id: "sta", name: "Stara Zagora" },
      { id: "tar", name: "Targovishte" }
    ],
    hr: [
      { id: "bjel", name: "Bjelovar" },
      { id: "var", name: "Varaždin" },
      { id: "vin", name: "Vinkovci" },
      { id: "vuk", name: "Vukovar" },
      { id: "dub", name: "Dubrovnik" },
      { id: "zad", name: "Zadar" },
      { id: "zag", name: "Zagreb" },
      { id: "kar", name: "Karlovac" },
      { id: "kop", name: "Koprivnica" },
      { id: "kra", name: "Krapina" },
      { id: "mak", name: "Makarska" },
      { id: "osi", name: "Osijek" },
      { id: "paz", name: "Pazin" },
      { id: "poz", name: "Požega" },
      { id: "pul", name: "Pula" },
      { id: "rij", name: "Rijeka" },
      { id: "sis", name: "Sisak" },
      { id: "spl", name: "Split" },
      { id: "shi", name: "Šibenik" },
      { id: "sla", name: "Slavonski Brod" },
      { id: "tro", name: "Trogir" },
      { id: "vir", name: "Virovitica" }
    ],
    sk: [
      { id: "ban", name: "Banská Bystrica" },
      { id: "bra", name: "Bratislava" },
      { id: "gal", name: "Galanta" },
      { id: "gel", name: "Gelnica" },
      { id: "dol", name: "Dolný Kubín" },
      { id: "zil", name: "Žilina" },
      { id: "zvo", name: "Zvolen" },
      { id: "kom", name: "Komárno" },
      { id: "kos", name: "Košice" },
      { id: "lev", name: "Levice" },
      { id: "lip", name: "Liptovský Mikuláš" },
      { id: "luc", name: "Lučenec" },
      { id: "mar", name: "Martin" },
      { id: "mic", name: "Michalovce" },
      { id: "nit", name: "Nitra" },
      { id: "nov", name: "Nové Zámky" },
      { id: "pop", name: "Poprad" },
      { id: "pre", name: "Prešov" },
      { id: "pri", name: "Prievidza" },
      { id: "roz", name: "Rožňava" },
      { id: "tre", name: "Trenčín" },
      { id: "trn", name: "Trnava" }
    ],
    ro: [
      { id: "ara", name: "Arad" },
      { id: "bac", name: "Bacău" },
      { id: "bra", name: "Brașov" },
      { id: "buc", name: "Bucharest" },
      { id: "gal", name: "Galați" },
      { id: "dec", name: "Deva" },
      { id: "ias", name: "Iași" },
      { id: "clu", name: "Cluj-Napoca" },
      { id: "con", name: "Constanța" },
      { id: "cra", name: "Craiova" },
      { id: "mag", name: "Mangalia" },
      { id: "med", name: "Mediaș" },
      { id: "ora", name: "Oradea" },
      { id: "pit", name: "Pitești" },
      { id: "plo", name: "Ploiești" },
      { id: "rim", name: "Râmnicu Vâlcea" },
      { id: "sib", name: "Sibiu" },
      { id: "suc", name: "Suceava" },
      { id: "tim", name: "Timișoara" },
      { id: "tir", name: "Târgu Mureș" },
      { id: "foc", name: "Focșani" },
      { id: "hun", name: "Hunedoara" }
    ],
    hu: [
      { id: "bek", name: "Békéscsaba" },
      { id: "bud", name: "Budapest" },
      { id: "vec", name: "Vác" },
      { id: "ves", name: "Veszprém" },
      { id: "deb", name: "Debrecen" },
      { id: "dun", name: "Dunaújváros" },
      { id: "kad", name: "Kaposvár" },
      { id: "kec", name: "Kecskemét" },
      { id: "mis", name: "Miskolc" },
      { id: "nad", name: "Nagykanizsa" },
      { id: "nic", name: "Nyíregyháza" },
      { id: "paz", name: "Paks" },
      { id: "pec", name: "Pécs" },
      { id: "sag", name: "Ságvár" },
      { id: "sal", name: "Salgótarján" },
      { id: "seg", name: "Szeged" },
      { id: "sek", name: "Székesfehérvár" },
      { id: "sol", name: "Szolnok" },
      { id: "som", name: "Szombathely" },
      { id: "sop", name: "Sopron" },
      { id: "tat", name: "Tatabánya" },
      { id: "zal", name: "Zalaegerszeg" }
    ],
    cz: [
      { id: "brn", name: "Brno" },
      { id: "dec", name: "Děčín" },
      { id: "zli", name: "Zlín" },
      { id: "jih", name: "Jihlava" },
      { id: "kar", name: "Karlovy Vary" },
      { id: "kla", name: "Kladno" },
      { id: "kol", name: "Kolín" },
      { id: "lib", name: "Liberec" },
      { id: "lit", name: "Litoměřice" },
      { id: "mol", name: "Mladá Boleslav" },
      { id: "mos", name: "Most" },
      { id: "olo", name: "Olomouc" },
      { id: "opa", name: "Opava" },
      { id: "ost", name: "Ostrava" },
      { id: "par", name: "Pardubice" },
      { id: "pil", name: "Plzeň" },
      { id: "pra", name: "Prague" },
      { id: "pro", name: "Prostějov" },
      { id: "tab", name: "Tábor" },
      { id: "tep", name: "Teplice" },
      { id: "usl", name: "Ústí nad Labem" },
      { id: "hra", name: "Hradec Králové" }
    ]
  },
  es: {
    bg: [
      { id: "burg", name: "Burgas" },
      { id: "var", name: "Varna" },
      { id: "vel", name: "Veliko Tarnovo" },
      { id: "vid", name: "Vidin" },
      { id: "vrа", name: "Vratsa" },
      { id: "gab", name: "Gabrovo" },
      { id: "dob", name: "Dobrich" },
      { id: "kar", name: "Karlovo" },
      { id: "kaz", name: "Kazanlak" },
      { id: "kyr", name: "Kardzhali" },
      { id: "kus", name: "Kyustendil" },
      { id: "lov", name: "Lovech" },
      { id: "mon", name: "Montana" },
      { id: "paz", name: "Pazardzhik" },
      { id: "per", name: "Pernik" },
      { id: "ple", name: "Pleven" },
      { id: "plo", name: "Plovdiv" },
      { id: "raz", name: "Razgrad" },
      { id: "rou", name: "Ruse" },
      { id: "sil", name: "Silistra" },
      { id: "sli", name: "Sliven" },
      { id: "smo", name: "Smolyan" },
      { id: "sof", name: "Sofía" },
      { id: "sta", name: "Stara Zagora" },
      { id: "tar", name: "Targovishte" }
    ],
    hr: [
      { id: "bjel", name: "Bjelovar" },
      { id: "var", name: "Varaždin" },
      { id: "vin", name: "Vinkovci" },
      { id: "vuk", name: "Vukovar" },
      { id: "dub", name: "Dubrovnik" },
      { id: "zad", name: "Zadar" },
      { id: "zag", name: "Zagreb" },
      { id: "kar", name: "Karlovac" },
      { id: "kop", name: "Koprivnica" },
      { id: "kra", name: "Krapina" },
      { id: "mak", name: "Makarska" },
      { id: "osi", name: "Osijek" },
      { id: "paz", name: "Pazin" },
      { id: "poz", name: "Požega" },
      { id: "pul", name: "Pula" },
      { id: "rij", name: "Rijeka" },
      { id: "sis", name: "Sisak" },
      { id: "spl", name: "Split" },
      { id: "shi", name: "Šibenik" },
      { id: "sla", name: "Slavonski Brod" },
      { id: "tro", name: "Trogir" },
      { id: "vir", name: "Virovitica" }
    ],
    sk: [
      { id: "ban", name: "Banská Bystrica" },
      { id: "bra", name: "Bratislava" },
      { id: "gal", name: "Galanta" },
      { id: "gel", name: "Gelnica" },
      { id: "dol", name: "Dolný Kubín" },
      { id: "zil", name: "Žilina" },
      { id: "zvo", name: "Zvolen" },
      { id: "kom", name: "Komárno" },
      { id: "kos", name: "Košice" },
      { id: "lev", name: "Levice" },
      { id: "lip", name: "Liptovský Mikuláš" },
      { id: "luc", name: "Lučenec" },
      { id: "mar", name: "Martin" },
      { id: "mic", name: "Michalovce" },
      { id: "nit", name: "Nitra" },
      { id: "nov", name: "Nové Zámky" },
      { id: "pop", name: "Poprad" },
      { id: "pre", name: "Prešov" },
      { id: "pri", name: "Prievidza" },
      { id: "roz", name: "Rožňava" },
      { id: "tre", name: "Trenčín" },
      { id: "trn", name: "Trnava" }
    ],
    ro: [
      { id: "ara", name: "Arad" },
      { id: "bac", name: "Bacău" },
      { id: "bra", name: "Brașov" },
      { id: "buc", name: "Bucarest" },
      { id: "gal", name: "Galați" },
      { id: "dec", name: "Deva" },
      { id: "ias", name: "Iași" },
      { id: "clu", name: "Cluj-Napoca" },
      { id: "con", name: "Constanța" },
      { id: "cra", name: "Craiova" },
      { id: "mag", name: "Mangalia" },
      { id: "med", name: "Mediaș" },
      { id: "ora", name: "Oradea" },
      { id: "pit", name: "Pitești" },
      { id: "plo", name: "Ploiești" },
      { id: "rim", name: "Râmnicu Vâlcea" },
      { id: "sib", name: "Sibiu" },
      { id: "suc", name: "Suceava" },
      { id: "tim", name: "Timișoara" },
      { id: "tir", name: "Târgu Mureș" },
      { id: "foc", name: "Focșani" },
      { id: "hun", name: "Hunedoara" }
    ],
    hu: [
      { id: "bek", name: "Békéscsaba" },
      { id: "bud", name: "Budapest" },
      { id: "vec", name: "Vác" },
      { id: "ves", name: "Veszprém" },
      { id: "deb", name: "Debrecen" },
      { id: "dun", name: "Dunaújváros" },
      { id: "kad", name: "Kaposvár" },
      { id: "kec", name: "Kecskemét" },
      { id: "mis", name: "Miskolc" },
      { id: "nad", name: "Nagykanizsa" },
      { id: "nic", name: "Nyíregyháza" },
      { id: "paz", name: "Paks" },
      { id: "pec", name: "Pécs" },
      { id: "sag", name: "Ságvár" },
      { id: "sal", name: "Salgótarján" },
      { id: "seg", name: "Szeged" },
      { id: "sek", name: "Székesfehérvár" },
      { id: "sol", name: "Szolnok" },
      { id: "som", name: "Szombathely" },
      { id: "sop", name: "Sopron" },
      { id: "tat", name: "Tatabánya" },
      { id: "zal", name: "Zalaegerszeg" }
    ],
    cz: [
      { id: "brn", name: "Brno" },
      { id: "dec", name: "Děčín" },
      { id: "zli", name: "Zlín" },
      { id: "jih", name: "Jihlava" },
      { id: "kar", name: "Karlovy Vary" },
      { id: "kla", name: "Kladno" },
      { id: "kol", name: "Kolín" },
      { id: "lib", name: "Liberec" },
      { id: "lit", name: "Litoměřice" },
      { id: "mol", name: "Mladá Boleslav" },
      { id: "mos", name: "Most" },
      { id: "olo", name: "Olomouc" },
      { id: "opa", name: "Opava" },
      { id: "ost", name: "Ostrava" },
      { id: "par", name: "Pardubice" },
      { id: "pil", name: "Pilsen" },
      { id: "pra", name: "Praga" },
      { id: "pro", name: "Prostějov" },
      { id: "tab", name: "Tábor" },
      { id: "tep", name: "Teplice" },
      { id: "usl", name: "Ústí nad Labem" },
      { id: "hra", name: "Hradec Králové" }
    ]
  }
};
