import { CitiesByLang } from '../types';

export const northernEuropeCities: CitiesByLang = {
  ru: {
    gb: [
      { id: "lon", name: "Лондон" },
      { id: "man", name: "Манчестер" },
      { id: "bir", name: "Бирмингем" },
      { id: "liv", name: "Ливерпуль" },
      { id: "lee", name: "Лидс" },
      { id: "she", name: "Шеффилд" },
      { id: "bri", name: "Брайтон" },
      { id: "brs", name: "Бристоль" },
      { id: "cam", name: "Кембридж" },
      { id: "car", name: "Кардифф" },
      { id: "cov", name: "Ковентри" },
      { id: "der", name: "Дерби" },
      { id: "exe", name: "Эксетер" },
      { id: "gla", name: "Глазго" },
      { id: "lei", name: "Лестер" },
      { id: "new", name: "Ньюкасл" },
      { id: "not", name: "Ноттингем" },
      { id: "oxf", name: "Оксфорд" },
      { id: "ply", name: "Плимут" },
      { id: "por", name: "Портсмут" },
      { id: "rea", name: "Рединг" },
      { id: "sou", name: "Саутгемптон" },
      { id: "yor", name: "Йорк" },
      { id: "edi", name: "Эдинбург" },
      { id: "bel", name: "Белфаст" }
    ],
    ie: [
      { id: "dub", name: "Дублин" },
      { id: "cor", name: "Корк" },
      { id: "gal", name: "Голуэй" },
      { id: "lim", name: "Лимерик" },
      { id: "wat", name: "Уотерфорд" },
      { id: "dro", name: "Дроэда" },
      { id: "dun", name: "Дандолк" },
      { id: "sli", name: "Слайго" },
      { id: "kil", name: "Килкенни" },
      { id: "wex", name: "Уэксфорд" },
      { id: "ath", name: "Атлон" },
      { id: "car", name: "Карлоу" },
      { id: "enn", name: "Эннис" },
      { id: "let", name: "Леттеркенни" },
      { id: "mal", name: "Маллингар" },
      { id: "naa", name: "Наван" },
      { id: "por", name: "Портлиш" },
      { id: "tra", name: "Трали" },
      { id: "tul", name: "Талламор" },
      { id: "wick", name: "Уиклоу" },
      { id: "cas", name: "Каслбар" },
      { id: "mon", name: "Монахан" }
    ],
    fi: [
      { id: "hel", name: "Хельсинки" },
      { id: "esp", name: "Эспоо" },
      { id: "tam", name: "Тампере" },
      { id: "van", name: "Вантаа" },
      { id: "tur", name: "Турку" },
      { id: "oulu", name: "Оулу" },
      { id: "jyv", name: "Ювяскюля" },
      { id: "lah", name: "Лахти" },
      { id: "kuo", name: "Куопио" },
      { id: "por", name: "Пори" },
      { id: "joen", name: "Йоэнсуу" },
      { id: "lap", name: "Лаппеэнранта" },
      { id: "rov", name: "Рованиеми" },
      { id: "vaa", name: "Вааса" },
      { id: "kot", name: "Котка" },
      { id: "mik", name: "Миккели" },
      { id: "salo", name: "Сало" },
      { id: "sei", name: "Сейняйоки" },
      { id: "ham", name: "Хямеэнлинна" },
      { id: "kok", name: "Коккола" },
      { id: "kaa", name: "Каяани" },
      { id: "nur", name: "Нурмиярви" }
    ],
    dk: [
      { id: "cop", name: "Копенгаген" },
      { id: "aar", name: "Орхус" },
      { id: "ode", name: "Оденсе" },
      { id: "aal", name: "Ольборг" },
      { id: "esk", name: "Эсбьерг" },
      { id: "ran", name: "Раннерс" },
      { id: "kol", name: "Колдинг" },
      { id: "hor", name: "Хорсенс" },
      { id: "vej", name: "Вайле" },
      { id: "ros", name: "Роскилле" },
      { id: "her", name: "Хернинг" },
      { id: "sil", name: "Силькеборг" },
      { id: "nae", name: "Нествед" },
      { id: "hol", name: "Хольстебро" },
      { id: "koe", name: "Кёге" },
      { id: "sve", name: "Свендборг" },
      { id: "hjo", name: "Йёрринг" },
      { id: "fre", name: "Фредериксхавн" },
      { id: "vid", name: "Виборг" },
      { id: "ska", name: "Скандерборг" },
      { id: "nyk", name: "Нюкёбинг" },
      { id: "hil", name: "Хиллерёд" }
    ],
    se: [
      { id: "sto", name: "Стокгольм" },
      { id: "got", name: "Гётеборг" },
      { id: "mal", name: "Мальмё" },
      { id: "upp", name: "Уппсала" },
      { id: "lin", name: "Линчёпинг" },
      { id: "ore", name: "Эребру" },
      { id: "vas", name: "Вестерос" },
      { id: "hel", name: "Хельсингборг" },
      { id: "jon", name: "Йёнчёпинг" },
      { id: "nor", name: "Норрчёпинг" },
      { id: "lul", name: "Лулео" },
      { id: "ume", name: "Умео" },
      { id: "gav", name: "Евле" },
      { id: "bor", name: "Борос" },
      { id: "sod", name: "Сёдертелье" },
      { id: "sun", name: "Сундсвалль" },
      { id: "esk", name: "Эскильстуна" },
      { id: "kal", name: "Кальмар" },
      { id: "kar", name: "Карлстад" },
      { id: "hal", name: "Хальмстад" },
      { id: "ost", name: "Эстерсунд" },
      { id: "kir", name: "Кируна" }
    ],
    pl: [
      { id: "war", name: "Варшава" },
      { id: "kra", name: "Краков" },
      { id: "lod", name: "Лодзь" },
      { id: "wro", name: "Вроцлав" },
      { id: "poz", name: "Познань" },
      { id: "gda", name: "Гданьск" },
      { id: "szc", name: "Щецин" },
      { id: "byd", name: "Быдгощ" },
      { id: "lub", name: "Люблин" },
      { id: "kat", name: "Катовице" },
      { id: "bia", name: "Белосток" },
      { id: "gdy", name: "Гдыня" },
      { id: "cze", name: "Ченстохова" },
      { id: "rad", name: "Радом" },
      { id: "sos", name: "Сосновец" },
      { id: "tor", name: "Торунь" },
      { id: "kie", name: "Кельце" },
      { id: "gli", name: "Гливице" },
      { id: "rze", name: "Жешув" },
      { id: "zab", name: "Забже" },
      { id: "wal", name: "Валбжих" },
      { id: "plo", name: "Плоцк" }
    ],
    at: [
      { id: "vie", name: "Вена" },
      { id: "gra", name: "Грац" },
      { id: "lin", name: "Линц" },
      { id: "sal", name: "Зальцбург" },
      { id: "inn", name: "Инсбрук" },
      { id: "kla", name: "Клагенфурт" },
      { id: "vil", name: "Филлах" },
      { id: "wel", name: "Вельс" },
      { id: "don", name: "Дорнбирн" },
      { id: "wne", name: "Винер-Нойштадт" },
      { id: "ste", name: "Штайр" },
      { id: "fel", name: "Фельдкирх" },
      { id: "bra", name: "Брегенц" },
      { id: "leo", name: "Леондинг" },
      { id: "bad", name: "Баден" },
      { id: "wol", name: "Вольфсберг" },
      { id: "lus", name: "Лустенау" },
      { id: "kun", name: "Кундль" },
      { id: "kre", name: "Кремс" },
      { id: "tra", name: "Траун" },
      { id: "san", name: "Санкт-Пёльтен" },
      { id: "mod", name: "Мёдлинг" }
    ]
  },
  en: {
    gb: [
      { id: "lon", name: "London" },
      { id: "man", name: "Manchester" },
      { id: "bir", name: "Birmingham" },
      { id: "liv", name: "Liverpool" },
      { id: "lee", name: "Leeds" },
      { id: "she", name: "Sheffield" },
      { id: "bri", name: "Brighton" },
      { id: "brs", name: "Bristol" },
      { id: "cam", name: "Cambridge" },
      { id: "car", name: "Cardiff" },
      { id: "cov", name: "Coventry" },
      { id: "der", name: "Derby" },
      { id: "exe", name: "Exeter" },
      { id: "gla", name: "Glasgow" },
      { id: "lei", name: "Leicester" },
      { id: "new", name: "Newcastle" },
      { id: "not", name: "Nottingham" },
      { id: "oxf", name: "Oxford" },
      { id: "ply", name: "Plymouth" },
      { id: "por", name: "Portsmouth" },
      { id: "rea", name: "Reading" },
      { id: "sou", name: "Southampton" },
      { id: "yor", name: "York" },
      { id: "edi", name: "Edinburgh" },
      { id: "bel", name: "Belfast" }
    ],
    ie: [
      { id: "dub", name: "Dublin" },
      { id: "cor", name: "Cork" },
      { id: "gal", name: "Galway" },
      { id: "lim", name: "Limerick" },
      { id: "wat", name: "Waterford" },
      { id: "dro", name: "Drogheda" },
      { id: "dun", name: "Dundalk" },
      { id: "sli", name: "Sligo" },
      { id: "kil", name: "Kilkenny" },
      { id: "wex", name: "Wexford" },
      { id: "ath", name: "Athlone" },
      { id: "car", name: "Carlow" },
      { id: "enn", name: "Ennis" },
      { id: "let", name: "Letterkenny" },
      { id: "mal", name: "Mullingar" },
      { id: "naa", name: "Navan" },
      { id: "por", name: "Portlaoise" },
      { id: "tra", name: "Tralee" },
      { id: "tul", name: "Tullamore" },
      { id: "wick", name: "Wicklow" },
      { id: "cas", name: "Castlebar" },
      { id: "mon", name: "Monaghan" }
    ],
    fi: [
      { id: "hel", name: "Helsinki" },
      { id: "esp", name: "Espoo" },
      { id: "tam", name: "Tampere" },
      { id: "van", name: "Vantaa" },
      { id: "tur", name: "Turku" },
      { id: "oulu", name: "Oulu" },
      { id: "jyv", name: "Jyväskylä" },
      { id: "lah", name: "Lahti" },
      { id: "kuo", name: "Kuopio" },
      { id: "por", name: "Pori" },
      { id: "joen", name: "Joensuu" },
      { id: "lap", name: "Lappeenranta" },
      { id: "rov", name: "Rovaniemi" },
      { id: "vaa", name: "Vaasa" },
      { id: "kot", name: "Kotka" },
      { id: "mik", name: "Mikkeli" },
      { id: "salo", name: "Salo" },
      { id: "sei", name: "Seinäjoki" },
      { id: "ham", name: "Hämeenlinna" },
      { id: "kok", name: "Kokkola" },
      { id: "kaa", name: "Kajaani" },
      { id: "nur", name: "Nurmijärvi" }
    ],
    dk: [
      { id: "cop", name: "Copenhagen" },
      { id: "aar", name: "Aarhus" },
      { id: "ode", name: "Odense" },
      { id: "aal", name: "Aalborg" },
      { id: "esk", name: "Esbjerg" },
      { id: "ran", name: "Randers" },
      { id: "kol", name: "Kolding" },
      { id: "hor", name: "Horsens" },
      { id: "vej", name: "Vejle" },
      { id: "ros", name: "Roskilde" },
      { id: "her", name: "Herning" },
      { id: "sil", name: "Silkeborg" },
      { id: "nae", name: "Næstved" },
      { id: "hol", name: "Holstebro" },
      { id: "koe", name: "Køge" },
      { id: "sve", name: "Svendborg" },
      { id: "hjo", name: "Hjørring" },
      { id: "fre", name: "Frederikshavn" },
      { id: "vid", name: "Viborg" },
      { id: "ska", name: "Skanderborg" },
      { id: "nyk", name: "Nykøbing" },
      { id: "hil", name: "Hillerød" }
    ],
    se: [
      { id: "sto", name: "Stockholm" },
      { id: "got", name: "Gothenburg" },
      { id: "mal", name: "Malmö" },
      { id: "upp", name: "Uppsala" },
      { id: "lin", name: "Linköping" },
      { id: "ore", name: "Örebro" },
      { id: "vas", name: "Västerås" },
      { id: "hel", name: "Helsingborg" },
      { id: "jon", name: "Jönköping" },
      { id: "nor", name: "Norrköping" },
      { id: "lul", name: "Luleå" },
      { id: "ume", name: "Umeå" },
      { id: "gav", name: "Gävle" },
      { id: "bor", name: "Borås" },
      { id: "sod", name: "Södertälje" },
      { id: "sun", name: "Sundsvall" },
      { id: "esk", name: "Eskilstuna" },
      { id: "kal", name: "Kalmar" },
      { id: "kar", name: "Karlstad" },
      { id: "hal", name: "Halmstad" },
      { id: "ost", name: "Östersund" },
      { id: "kir", name: "Kiruna" }
    ],
    pl: [
      { id: "war", name: "Warsaw" },
      { id: "kra", name: "Kraków" },
      { id: "lod", name: "Łódź" },
      { id: "wro", name: "Wrocław" },
      { id: "poz", name: "Poznań" },
      { id: "gda", name: "Gdańsk" },
      { id: "szc", name: "Szczecin" },
      { id: "byd", name: "Bydgoszcz" },
      { id: "lub", name: "Lublin" },
      { id: "kat", name: "Katowice" },
      { id: "bia", name: "Białystok" },
      { id: "gdy", name: "Gdynia" },
      { id: "cze", name: "Częstochowa" },
      { id: "rad", name: "Radom" },
      { id: "sos", name: "Sosnowiec" },
      { id: "tor", name: "Toruń" },
      { id: "kie", name: "Kielce" },
      { id: "gli", name: "Gliwice" },
      { id: "rze", name: "Rzeszów" },
      { id: "zab", name: "Zabrze" },
      { id: "wal", name: "Wałbrzych" },
      { id: "plo", name: "Płock" }
    ],
    at: [
      { id: "vie", name: "Vienna" },
      { id: "gra", name: "Graz" },
      { id: "lin", name: "Linz" },
      { id: "sal", name: "Salzburg" },
      { id: "inn", name: "Innsbruck" },
      { id: "kla", name: "Klagenfurt" },
      { id: "vil", name: "Villach" },
      { id: "wel", name: "Wels" },
      { id: "don", name: "Dornbirn" },
      { id: "wne", name: "Wiener Neustadt" },
      { id: "ste", name: "Steyr" },
      { id: "fel", name: "Feldkirch" },
      { id: "bra", name: "Bregenz" },
      { id: "leo", name: "Leonding" },
      { id: "bad", name: "Baden" },
      { id: "wol", name: "Wolfsberg" },
      { id: "lus", name: "Lustenau" },
      { id: "kun", name: "Kufstein" },
      { id: "kre", name: "Krems" },
      { id: "tra", name: "Traun" },
      { id: "san", name: "Sankt Pölten" },
      { id: "mod", name: "Mödling" }
    ]
  },
  es: {
    gb: [
      { id: "lon", name: "Londres" },
      { id: "man", name: "Manchester" },
      { id: "bir", name: "Birmingham" },
      { id: "liv", name: "Liverpool" },
      { id: "lee", name: "Leeds" },
      { id: "she", name: "Sheffield" },
      { id: "bri", name: "Brighton" },
      { id: "brs", name: "Bristol" },
      { id: "cam", name: "Cambridge" },
      { id: "car", name: "Cardiff" },
      { id: "cov", name: "Coventry" },
      { id: "der", name: "Derby" },
      { id: "exe", name: "Exeter" },
      { id: "gla", name: "Glasgow" },
      { id: "lei", name: "Leicester" },
      { id: "new", name: "Newcastle" },
      { id: "not", name: "Nottingham" },
      { id: "oxf", name: "Oxford" },
      { id: "ply", name: "Plymouth" },
      { id: "por", name: "Portsmouth" },
      { id: "rea", name: "Reading" },
      { id: "sou", name: "Southampton" },
      { id: "yor", name: "York" },
      { id: "edi", name: "Edimburgo" },
      { id: "bel", name: "Belfast" }
    ],
    ie: [
      { id: "dub", name: "Dublín" },
      { id: "cor", name: "Cork" },
      { id: "gal", name: "Galway" },
      { id: "lim", name: "Limerick" },
      { id: "wat", name: "Waterford" },
      { id: "dro", name: "Drogheda" },
      { id: "dun", name: "Dundalk" },
      { id: "sli", name: "Sligo" },
      { id: "kil", name: "Kilkenny" },
      { id: "wex", name: "Wexford" },
      { id: "ath", name: "Athlone" },
      { id: "car", name: "Carlow" },
      { id: "enn", name: "Ennis" },
      { id: "let", name: "Letterkenny" },
      { id: "mal", name: "Mullingar" },
      { id: "naa", name: "Navan" },
      { id: "por", name: "Portlaoise" },
      { id: "tra", name: "Tralee" },
      { id: "tul", name: "Tullamore" },
      { id: "wick", name: "Wicklow" },
      { id: "cas", name: "Castlebar" },
      { id: "mon", name: "Monaghan" }
    ],
    fi: [
      { id: "hel", name: "Helsinki" },
      { id: "esp", name: "Espoo" },
      { id: "tam", name: "Tampere" },
      { id: "van", name: "Vantaa" },
      { id: "tur", name: "Turku" },
      { id: "oulu", name: "Oulu" },
      { id: "jyv", name: "Jyväskylä" },
      { id: "lah", name: "Lahti" },
      { id: "kuo", name: "Kuopio" },
      { id: "por", name: "Pori" },
      { id: "joen", name: "Joensuu" },
      { id: "lap", name: "Lappeenranta" },
      { id: "rov", name: "Rovaniemi" },
      { id: "vaa", name: "Vaasa" },
      { id: "kot", name: "Kotka" },
      { id: "mik", name: "Mikkeli" },
      { id: "salo", name: "Salo" },
      { id: "sei", name: "Seinäjoki" },
      { id: "ham", name: "Hämeenlinna" },
      { id: "kok", name: "Kokkola" },
      { id: "kaa", name: "Kajaani" },
      { id: "nur", name: "Nurmijärvi" }
    ],
    dk: [
      { id: "cop", name: "Copenhague" },
      { id: "aar", name: "Aarhus" },
      { id: "ode", name: "Odense" },
      { id: "aal", name: "Aalborg" },
      { id: "esk", name: "Esbjerg" },
      { id: "ran", name: "Randers" },
      { id: "kol", name: "Kolding" },
      { id: "hor", name: "Horsens" },
      { id: "vej", name: "Vejle" },
      { id: "ros", name: "Roskilde" },
      { id: "her", name: "Herning" },
      { id: "sil", name: "Silkeborg" },
      { id: "nae", name: "Næstved" },
      { id: "hol", name: "Holstebro" },
      { id: "koe", name: "Køge" },
      { id: "sve", name: "Svendborg" },
      { id: "hjo", name: "Hjørring" },
      { id: "fre", name: "Frederikshavn" },
      { id: "vid", name: "Viborg" },
      { id: "ska", name: "Skanderborg" },
      { id: "nyk", name: "Nykøbing" },
      { id: "hil", name: "Hillerød" }
    ],
    se: [
      { id: "sto", name: "Estocolmo" },
      { id: "got", name: "Gotemburgo" },
      { id: "mal", name: "Malmö" },
      { id: "upp", name: "Uppsala" },
      { id: "lin", name: "Linköping" },
      { id: "ore", name: "Örebro" },
      { id: "vas", name: "Västerås" },
      { id: "hel", name: "Helsingborg" },
      { id: "jon", name: "Jönköping" },
      { id: "nor", name: "Norrköping" },
      { id: "lul", name: "Luleå" },
      { id: "ume", name: "Umeå" },
      { id: "gav", name: "Gävle" },
      { id: "bor", name: "Borås" },
      { id: "sod", name: "Södertälje" },
      { id: "sun", name: "Sundsvall" },
      { id: "esk", name: "Eskilstuna" },
      { id: "kal", name: "Kalmar" },
      { id: "kar", name: "Karlstad" },
      { id: "hal", name: "Halmstad" },
      { id: "ost", name: "Östersund" },
      { id: "kir", name: "Kiruna" }
    ],
    pl: [
      { id: "war", name: "Varsovia" },
      { id: "kra", name: "Cracovia" },
      { id: "lod", name: "Lodz" },
      { id: "wro", name: "Breslavia" },
      { id: "poz", name: "Poznan" },
      { id: "gda", name: "Gdansk" },
      { id: "szc", name: "Szczecin" },
      { id: "byd", name: "Bydgoszcz" },
      { id: "lub", name: "Lublin" },
      { id: "kat", name: "Katowice" },
      { id: "bia", name: "Bialystok" },
      { id: "gdy", name: "Gdynia" },
      { id: "cze", name: "Czestochowa" },
      { id: "rad", name: "Radom" },
      { id: "sos", name: "Sosnowiec" },
      { id: "tor", name: "Torun" },
      { id: "kie", name: "Kielce" },
      { id: "gli", name: "Gliwice" },
      { id: "rze", name: "Rzeszow" },
      { id: "zab", name: "Zabrze" },
      { id: "wal", name: "Walbrzych" },
      { id: "plo", name: "Płock" }
    ],
    at: [
      { id: "vie", name: "Viena" },
      { id: "gra", name: "Graz" },
      { id: "lin", name: "Linz" },
      { id: "sal", name: "Salzburgo" },
      { id: "inn", name: "Innsbruck" },
      { id: "kla", name: "Klagenfurt" },
      { id: "vil", name: "Villach" },
      { id: "wel", name: "Wels" },
      { id: "don", name: "Dornbirn" },
      { id: "wne", name: "Wiener Neustadt" },
      { id: "ste", name: "Steyr" },
      { id: "fel", name: "Feldkirch" },
      { id: "bra", name: "Bregenz" },
      { id: "leo", name: "Leonding" },
      { id: "bad", name: "Baden" },
      { id: "wol", name: "Wolfsberg" },
      { id: "lus", name: "Lustenau" },
      { id: "kun", name: "Kufstein" },
      { id: "kre", name: "Krems" },
      { id: "tra", name: "Traun" },
      { id: "san", name: "Sankt Pölten" },
      { id: "mod", name: "Mödling" }
    ]
  }
};
