
import { CitiesByLang } from '../types';

export const southernEuropeCities: CitiesByLang = {
  ru: {
    it: [
      { id: "rom", name: "Рим" },
      { id: "mil", name: "Милан" },
      { id: "nap", name: "Неаполь" },
      { id: "tur", name: "Турин" },
      { id: "pal", name: "Палермо" },
      { id: "gen", name: "Генуя" },
      { id: "bol", name: "Болонья" },
      { id: "flo", name: "Флоренция" },
      { id: "bar", name: "Бари" },
      { id: "cat", name: "Катания" },
      { id: "ven", name: "Венеция" },
      { id: "ver", name: "Верона" },
      { id: "mes", name: "Мессина" },
      { id: "pad", name: "Падуя" },
      { id: "tri", name: "Триест" },
      { id: "bre", name: "Брешиа" },
      { id: "par", name: "Парма" },
      { id: "tar", name: "Таранто" },
      { id: "reg", name: "Реджо-ди-Калабрия" },
      { id: "mod", name: "Модена" }
    ],
    es: [
      { id: "mad", name: "Мадрид" },
      { id: "bcn", name: "Барселона" },
      { id: "val", name: "Валенсия" },
      { id: "sev", name: "Севилья" },
      { id: "zar", name: "Сарагоса" },
      { id: "mal", name: "Малага" },
      { id: "mur", name: "Мурсия" },
      { id: "pma", name: "Пальма" },
      { id: "lpa", name: "Лас-Пальмас" },
      { id: "bil", name: "Бильбао" },
      { id: "ali", name: "Аликанте" },
      { id: "cor", name: "Кордова" },
      { id: "val", name: "Вальядолид" },
      { id: "vgo", name: "Виго" },
      { id: "gij", name: "Хихон" }
    ],
    pt: [
      { id: "lis", name: "Лиссабон" },
      { id: "por", name: "Порту" },
      { id: "vil", name: "Вила-Нова-ди-Гая" },
      { id: "ama", name: "Амадора" },
      { id: "bra", name: "Брага" },
      { id: "set", name: "Сетубал" },
      { id: "coi", name: "Коимбра" },
      { id: "fun", name: "Фуншал" },
      { id: "lei", name: "Лейрия" },
      { id: "evo", name: "Эвора" },
      { id: "far", name: "Фару" },
      { id: "ave", name: "Авейру" },
      { id: "vis", name: "Визеу" },
      { id: "por", name: "Порталегре" },
      { id: "bej", name: "Бежа" }
    ],
    gr: [
      { id: "ath", name: "Афины" },
      { id: "the", name: "Салоники" },
      { id: "pat", name: "Патры" },
      { id: "her", name: "Ираклион" },
      { id: "lar", name: "Лариса" },
      { id: "vol", name: "Волос" },
      { id: "ioa", name: "Янина" },
      { id: "tri", name: "Трикала" },
      { id: "cha", name: "Ханья" },
      { id: "cha", name: "Халкида" },
      { id: "ale", name: "Александруполис" },
      { id: "kav", name: "Кавала" },
      { id: "kal", name: "Каламата" },
      { id: "ser", name: "Серре" },
      { id: "lam", name: "Ламия" }
    ]
  },
  en: {
    it: [
      { id: "rom", name: "Rome" },
      { id: "mil", name: "Milan" },
      { id: "nap", name: "Naples" },
      { id: "tur", name: "Turin" },
      { id: "pal", name: "Palermo" },
      { id: "gen", name: "Genoa" },
      { id: "bol", name: "Bologna" },
      { id: "flo", name: "Florence" },
      { id: "bar", name: "Bari" },
      { id: "cat", name: "Catania" },
      { id: "ven", name: "Venice" },
      { id: "ver", name: "Verona" },
      { id: "mes", name: "Messina" },
      { id: "pad", name: "Padua" },
      { id: "tri", name: "Trieste" },
      { id: "bre", name: "Brescia" },
      { id: "par", name: "Parma" },
      { id: "tar", name: "Taranto" },
      { id: "reg", name: "Reggio Calabria" },
      { id: "mod", name: "Modena" }
    ],
    es: [
      { id: "mad", name: "Madrid" },
      { id: "bcn", name: "Barcelona" },
      { id: "val", name: "Valencia" },
      { id: "sev", name: "Seville" },
      { id: "zar", name: "Zaragoza" },
      { id: "mal", name: "Málaga" },
      { id: "mur", name: "Murcia" },
      { id: "pma", name: "Palma" },
      { id: "lpa", name: "Las Palmas" },
      { id: "bil", name: "Bilbao" },
      { id: "ali", name: "Alicante" },
      { id: "cor", name: "Córdoba" },
      { id: "val", name: "Valladolid" },
      { id: "vgo", name: "Vigo" },
      { id: "gij", name: "Gijón" }
    ],
    pt: [
      { id: "lis", name: "Lisbon" },
      { id: "por", name: "Porto" },
      { id: "vil", name: "Vila Nova de Gaia" },
      { id: "ama", name: "Amadora" },
      { id: "bra", name: "Braga" },
      { id: "set", name: "Setúbal" },
      { id: "coi", name: "Coimbra" },
      { id: "fun", name: "Funchal" },
      { id: "lei", name: "Leiria" },
      { id: "evo", name: "Évora" },
      { id: "far", name: "Faro" },
      { id: "ave", name: "Aveiro" },
      { id: "vis", name: "Viseu" },
      { id: "por", name: "Portalegre" },
      { id: "bej", name: "Beja" }
    ],
    gr: [
      { id: "ath", name: "Athens" },
      { id: "the", name: "Thessaloniki" },
      { id: "pat", name: "Patras" },
      { id: "her", name: "Heraklion" },
      { id: "lar", name: "Larissa" },
      { id: "vol", name: "Volos" },
      { id: "ioa", name: "Ioannina" },
      { id: "tri", name: "Trikala" },
      { id: "cha", name: "Chania" },
      { id: "cha", name: "Chalcis" },
      { id: "ale", name: "Alexandroupoli" },
      { id: "kav", name: "Kavala" },
      { id: "kal", name: "Kalamata" },
      { id: "ser", name: "Serres" },
      { id: "lam", name: "Lamia" }
    ]
  },
  es: {
    it: [
      { id: "rom", name: "Roma" },
      { id: "mil", name: "Milán" },
      { id: "nap", name: "Nápoles" },
      { id: "tur", name: "Turín" },
      { id: "pal", name: "Palermo" },
      { id: "gen", name: "Génova" },
      { id: "bol", name: "Bolonia" },
      { id: "flo", name: "Florencia" },
      { id: "bar", name: "Bari" },
      { id: "cat", name: "Catania" },
      { id: "ven", name: "Venecia" },
      { id: "ver", name: "Verona" },
      { id: "mes", name: "Mesina" },
      { id: "pad", name: "Padua" },
      { id: "tri", name: "Trieste" },
      { id: "bre", name: "Brescia" },
      { id: "par", name: "Parma" },
      { id: "tar", name: "Tarento" },
      { id: "reg", name: "Reggio Calabria" },
      { id: "mod", name: "Módena" }
    ],
    es: [
      { id: "mad", name: "Madrid" },
      { id: "bcn", name: "Barcelona" },
      { id: "val", name: "Valencia" },
      { id: "sev", name: "Sevilla" },
      { id: "zar", name: "Zaragoza" },
      { id: "mal", name: "Málaga" },
      { id: "mur", name: "Murcia" },
      { id: "pma", name: "Palma" },
      { id: "lpa", name: "Las Palmas" },
      { id: "bil", name: "Bilbao" },
      { id: "ali", name: "Alicante" },
      { id: "cor", name: "Córdoba" },
      { id: "val", name: "Valladolid" },
      { id: "vgo", name: "Vigo" },
      { id: "gij", name: "Gijón" }
    ],
    pt: [
      { id: "lis", name: "Lisboa" },
      { id: "por", name: "Oporto" },
      { id: "vil", name: "Vila Nova de Gaia" },
      { id: "ama", name: "Amadora" },
      { id: "bra", name: "Braga" },
      { id: "set", name: "Setúbal" },
      { id: "coi", name: "Coímbra" },
      { id: "fun", name: "Funchal" },
      { id: "lei", name: "Leiria" },
      { id: "evo", name: "Évora" },
      { id: "far", name: "Faro" },
      { id: "ave", name: "Aveiro" },
      { id: "vis", name: "Viseu" },
      { id: "por", name: "Portalegre" },
      { id: "bej", name: "Beja" }
    ],
    gr: [
      { id: "ath", name: "Atenas" },
      { id: "the", name: "Tesalónica" },
      { id: "pat", name: "Patras" },
      { id: "her", name: "Heraklion" },
      { id: "lar", name: "Larisa" },
      { id: "vol", name: "Volos" },
      { id: "ioa", name: "Ioannina" },
      { id: "tri", name: "Trikala" },
      { id: "cha", name: "Chania" },
      { id: "cha", name: "Chalcis" },
      { id: "ale", name: "Alexandroupolis" },
      { id: "kav", name: "Kavala" },
      { id: "kal", name: "Kalamata" },
      { id: "ser", name: "Serres" },
      { id: "lam", name: "Lamia" }
    ]
  }
};
