
import { CitiesByLang } from '../types';

export const southernEuropeCities: CitiesByLang = {
  ru: {
    it: [
      { id: "anc", name: "Анкона" },
      { id: "bar", name: "Бари" },
      { id: "ber", name: "Бергамо" },
      { id: "bol", name: "Болонья" },
      { id: "bre", name: "Брешиа" },
      { id: "ven", name: "Венеция" },
      { id: "ver", name: "Верона" },
      { id: "gen", name: "Генуя" },
      { id: "cat", name: "Катания" },
      { id: "liv", name: "Ливорно" },
      { id: "lec", name: "Лечче" },
      { id: "mes", name: "Мессина" },
      { id: "mil", name: "Милан" },
      { id: "mod", name: "Модена" },
      { id: "mon", name: "Монца" },
      { id: "nap", name: "Неаполь" },
      { id: "nov", name: "Новара" },
      { id: "pad", name: "Падуя" },
      { id: "pal", name: "Палермо" },
      { id: "par", name: "Парма" },
      { id: "per", name: "Перуджа" },
      { id: "pes", name: "Пескара" },
      { id: "pis", name: "Пиза" },
      { id: "pra", name: "Прато" },
      { id: "rav", name: "Равенна" },
      { id: "reg", name: "Реджо-ди-Калабрия" },
      { id: "rim", name: "Римини" },
      { id: "rom", name: "Рим" },
      { id: "sal", name: "Салерно" },
      { id: "sas", name: "Сассари" },
      { id: "sir", name: "Сиракузы" },
      { id: "tar", name: "Таранто" },
      { id: "ter", name: "Терни" },
      { id: "tri", name: "Триест" },
      { id: "tur", name: "Турин" },
      { id: "flo", name: "Флоренция" }
    ],
    es: [
      { id: "alc", name: "Алькала-де-Энарес" },
      { id: "ali", name: "Аликанте" },
      { id: "alm", name: "Альмерия" },
      { id: "bad", name: "Бадахос" },
      { id: "bcn", name: "Барселона" },
      { id: "bil", name: "Бильбао" },
      { id: "val", name: "Валенсия" },
      { id: "vgo", name: "Виго" },
      { id: "vit", name: "Витория" },
      { id: "gra", name: "Гранада" },
      { id: "elc", name: "Эльче" },
      { id: "jer", name: "Херес-де-ла-Фронтера" },
      { id: "cor", name: "Кордова" },
      { id: "lac", name: "Ла-Корунья" },
      { id: "lpa", name: "Лас-Пальмас" },
      { id: "leg", name: "Леганес" },
      { id: "leo", name: "Леон" },
      { id: "log", name: "Логроньо" },
      { id: "mad", name: "Мадрид" },
      { id: "mal", name: "Малага" },
      { id: "mos", name: "Мостолес" },
      { id: "mur", name: "Мурсия" },
      { id: "our", name: "Оуренсе" },
      { id: "ovi", name: "Овьедо" },
      { id: "pma", name: "Пальма" },
      { id: "pam", name: "Памплона" },
      { id: "pon", name: "Понтеведра" },
      { id: "sal", name: "Саламанка" },
      { id: "ssc", name: "Сан-Себастьян" },
      { id: "scq", name: "Сантьяго-де-Компостела" },
      { id: "sev", name: "Севилья" },
      { id: "tar", name: "Таррагона" },
      { id: "ter", name: "Террасса" },
      { id: "val", name: "Вальядолид" },
      { id: "gij", name: "Хихон" },
      { id: "zar", name: "Сарагоса" }
    ],
    pt: [
      { id: "ave", name: "Авейру" },
      { id: "agu", name: "Агуэда" },
      { id: "alb", name: "Албуфейра" },
      { id: "alm", name: "Алмада" },
      { id: "ama", name: "Амадора" },
      { id: "bar", name: "Баррейру" },
      { id: "bej", name: "Бежа" },
      { id: "bra", name: "Брага" },
      { id: "brag", name: "Браганса" },
      { id: "vis", name: "Визеу" },
      { id: "vil", name: "Вила-Нова-ди-Гая" },
      { id: "vir", name: "Виана-ду-Каштелу" },
      { id: "gui", name: "Гимарайнш" },
      { id: "evo", name: "Эвора" },
      { id: "coi", name: "Коимбра" },
      { id: "lei", name: "Лейрия" },
      { id: "lis", name: "Лиссабон" },
      { id: "lou", name: "Лоуле" },
      { id: "mad", name: "Мадейра" },
      { id: "mat", name: "Матозиньюш" },
      { id: "ode", name: "Одивелаш" },
      { id: "oli", name: "Оливейра-ди-Аземейш" },
      { id: "por", name: "Порталегре" },
      { id: "porto", name: "Порту" },
      { id: "san", name: "Санта-Мария-да-Фейра" },
      { id: "set", name: "Сетубал" },
      { id: "sin", name: "Синтра" },
      { id: "tor", name: "Торреш-Ведраш" },
      { id: "far", name: "Фару" },
      { id: "fig", name: "Фигейра-да-Фош" },
      { id: "fun", name: "Фуншал" }
    ],
    gr: [
      { id: "agr", name: "Агринион" },
      { id: "ale", name: "Александруполис" },
      { id: "ath", name: "Афины" },
      { id: "vol", name: "Волос" },
      { id: "ver", name: "Верия" },
      { id: "gia", name: "Янина" },
      { id: "dra", name: "Драма" },
      { id: "ira", name: "Ираклион" },
      { id: "the", name: "Салоники" },
      { id: "kal", name: "Каламата" },
      { id: "kar", name: "Кардица" },
      { id: "kas", name: "Касторья" },
      { id: "kat", name: "Катерини" },
      { id: "kav", name: "Кавала" },
      { id: "ker", name: "Керкира" },
      { id: "kom", name: "Комотини" },
      { id: "cor", name: "Коринф" },
      { id: "cos", name: "Козани" },
      { id: "lam", name: "Ламия" },
      { id: "lar", name: "Лариса" },
      { id: "liv", name: "Ливадия" },
      { id: "mes", name: "Месолонгион" },
      { id: "met", name: "Метеора" },
      { id: "mit", name: "Митилини" },
      { id: "naf", name: "Нафплион" },
      { id: "pat", name: "Патры" },
      { id: "pir", name: "Пирей" },
      { id: "pre", name: "Превеза" },
      { id: "ret", name: "Ретимнон" },
      { id: "rod", name: "Родос" },
      { id: "ser", name: "Серре" },
      { id: "spa", name: "Спарта" },
      { id: "tri", name: "Трикала" },
      { id: "tri", name: "Триполис" },
      { id: "flo", name: "Флорина" },
      { id: "cha", name: "Халкида" },
      { id: "cha", name: "Ханья" }
    ]
  },
  en: {
    it: [
      { id: "bar", name: "Bari" },
      { id: "bol", name: "Bologna" },
      { id: "bre", name: "Brescia" },
      { id: "cat", name: "Catania" },
      { id: "flo", name: "Florence" },
      { id: "gen", name: "Genoa" },
      { id: "mes", name: "Messina" },
      { id: "mil", name: "Milan" },
      { id: "mod", name: "Modena" },
      { id: "nap", name: "Naples" },
      { id: "pad", name: "Padua" },
      { id: "pal", name: "Palermo" },
      { id: "par", name: "Parma" },
      { id: "reg", name: "Reggio Calabria" },
      { id: "rom", name: "Rome" },
      { id: "tar", name: "Taranto" },
      { id: "tri", name: "Trieste" },
      { id: "tur", name: "Turin" },
      { id: "ven", name: "Venice" },
      { id: "ver", name: "Verona" }
    ],
    es: [
      { id: "ali", name: "Alicante" },
      { id: "bcn", name: "Barcelona" },
      { id: "bil", name: "Bilbao" },
      { id: "cor", name: "Córdoba" },
      { id: "gij", name: "Gijón" },
      { id: "lpa", name: "Las Palmas" },
      { id: "mad", name: "Madrid" },
      { id: "mal", name: "Málaga" },
      { id: "mur", name: "Murcia" },
      { id: "pma", name: "Palma" },
      { id: "sev", name: "Seville" },
      { id: "val", name: "Valencia" },
      { id: "val", name: "Valladolid" },
      { id: "vgo", name: "Vigo" },
      { id: "zar", name: "Zaragoza" }
    ],
    pt: [
      { id: "ama", name: "Amadora" },
      { id: "ave", name: "Aveiro" },
      { id: "bej", name: "Beja" },
      { id: "bra", name: "Braga" },
      { id: "coi", name: "Coimbra" },
      { id: "evo", name: "Évora" },
      { id: "far", name: "Faro" },
      { id: "fun", name: "Funchal" },
      { id: "lei", name: "Leiria" },
      { id: "lis", name: "Lisbon" },
      { id: "por", name: "Portalegre" },
      { id: "por", name: "Porto" },
      { id: "set", name: "Setúbal" },
      { id: "vil", name: "Vila Nova de Gaia" },
      { id: "vis", name: "Viseu" }
    ],
    gr: [
      { id: "ale", name: "Alexandroupoli" },
      { id: "ath", name: "Athens" },
      { id: "cha", name: "Chalcis" },
      { id: "cha", name: "Chania" },
      { id: "her", name: "Heraklion" },
      { id: "ioa", name: "Ioannina" },
      { id: "kal", name: "Kalamata" },
      { id: "kav", name: "Kavala" },
      { id: "lam", name: "Lamia" },
      { id: "lar", name: "Larissa" },
      { id: "pat", name: "Patras" },
      { id: "ser", name: "Serres" },
      { id: "the", name: "Thessaloniki" },
      { id: "tri", name: "Trikala" },
      { id: "vol", name: "Volos" }
    ]
  },
  es: {
    it: [
      { id: "bar", name: "Bari" },
      { id: "bol", name: "Bolonia" },
      { id: "bre", name: "Brescia" },
      { id: "cat", name: "Catania" },
      { id: "flo", name: "Florencia" },
      { id: "gen", name: "Génova" },
      { id: "mes", name: "Mesina" },
      { id: "mil", name: "Milán" },
      { id: "mod", name: "Módena" },
      { id: "nap", name: "Nápoles" },
      { id: "pad", name: "Padua" },
      { id: "pal", name: "Palermo" },
      { id: "par", name: "Parma" },
      { id: "reg", name: "Reggio Calabria" },
      { id: "rom", name: "Roma" },
      { id: "tar", name: "Tarento" },
      { id: "tri", name: "Trieste" },
      { id: "tur", name: "Turín" },
      { id: "ven", name: "Venecia" },
      { id: "ver", name: "Verona" }
    ],
    es: [
      { id: "ali", name: "Alicante" },
      { id: "bcn", name: "Barcelona" },
      { id: "bil", name: "Bilbao" },
      { id: "cor", name: "Córdoba" },
      { id: "gij", name: "Gijón" },
      { id: "lpa", name: "Las Palmas" },
      { id: "mad", name: "Madrid" },
      { id: "mal", name: "Málaga" },
      { id: "mur", name: "Murcia" },
      { id: "pma", name: "Palma" },
      { id: "sev", name: "Sevilla" },
      { id: "val", name: "Valencia" },
      { id: "val", name: "Valladolid" },
      { id: "vgo", name: "Vigo" },
      { id: "zar", name: "Zaragoza" }
    ],
    pt: [
      { id: "ama", name: "Amadora" },
      { id: "ave", name: "Aveiro" },
      { id: "bej", name: "Beja" },
      { id: "bra", name: "Braga" },
      { id: "coi", name: "Coímbra" },
      { id: "evo", name: "Évora" },
      { id: "far", name: "Faro" },
      { id: "fun", name: "Funchal" },
      { id: "lei", name: "Leiria" },
      { id: "lis", name: "Lisboa" },
      { id: "por", name: "Portalegre" },
      { id: "por", name: "Oporto" },
      { id: "set", name: "Setúbal" },
      { id: "vil", name: "Vila Nova de Gaia" },
      { id: "vis", name: "Viseu" }
    ],
    gr: [
      { id: "ale", name: "Alexandroupolis" },
      { id: "ath", name: "Atenas" },
      { id: "cha", name: "Chalcis" },
      { id: "cha", name: "Chania" },
      { id: "her", name: "Heraklion" },
      { id: "ioa", name: "Ioannina" },
      { id: "kal", name: "Kalamata" },
      { id: "kav", name: "Kavala" },
      { id: "lam", name: "Lamia" },
      { id: "lar", name: "Larisa" },
      { id: "pat", name: "Patras" },
      { id: "ser", name: "Serres" },
      { id: "the", name: "Tesalónica" },
      { id: "tri", name: "Trikala" },
      { id: "vol", name: "Volos" }
    ]
  }
};
