
import { CitiesByLang } from '../types';

export const westernEuropeCities: CitiesByLang = {
  ru: {
    de: [
      { id: "ber", name: "Берлин" },
      { id: "bil", name: "Билефельд" },
      { id: "boc", name: "Бохум" },
      { id: "bon", name: "Бонн" },
      { id: "bre", name: "Бремен" },
      { id: "wup", name: "Вупперталь" },
      { id: "ham", name: "Гамбург" },
      { id: "han", name: "Ганновер" },
      { id: "gel", name: "Гельзенкирхен" },
      { id: "dui", name: "Дуйсбург" },
      { id: "dus", name: "Дюссельдорф" },
      { id: "dor", name: "Дортмунд" },
      { id: "dre", name: "Дрезден" },
      { id: "jen", name: "Йена" },
      { id: "kai", name: "Кайзерслаутерн" },
      { id: "kar", name: "Карлсруэ" },
      { id: "kas", name: "Кассель" },
      { id: "kie", name: "Киль" },
      { id: "kob", name: "Кобленц" },
      { id: "col", name: "Кёльн" },
      { id: "lei", name: "Лейпциг" },
      { id: "lub", name: "Любек" },
      { id: "mag", name: "Магдебург" },
      { id: "man", name: "Маннгейм" },
      { id: "mun", name: "Мюнхен" },
      { id: "nur", name: "Нюрнберг" },
      { id: "ros", name: "Росток" },
      { id: "stu", name: "Штутгарт" },
      { id: "fra", name: "Франкфурт-на-Майне" },
      { id: "fri", name: "Фрайбург" }
    ],
    fr: [
      { id: "ang", name: "Анже" },
      { id: "ami", name: "Амьен" },
      { id: "bez", name: "Безансон" },
      { id: "bor", name: "Бордо" },
      { id: "bre", name: "Брест" },
      { id: "val", name: "Валансьен" },
      { id: "gre", name: "Гренобль" },
      { id: "dij", name: "Дижон" },
      { id: "dun", name: "Дюнкерк" },
      { id: "hav", name: "Гавр" },
      { id: "lil", name: "Лилль" },
      { id: "lim", name: "Лимож" },
      { id: "lyo", name: "Лион" },
      { id: "mar", name: "Марсель" },
      { id: "met", name: "Мец" },
      { id: "mon", name: "Монпелье" },
      { id: "nan", name: "Нант" },
      { id: "nim", name: "Ним" },
      { id: "nic", name: "Ницца" },
      { id: "orl", name: "Орлеан" },
      { id: "par", name: "Париж" },
      { id: "pau", name: "По" },
      { id: "per", name: "Перпиньян" },
      { id: "rei", name: "Реймс" },
      { id: "ren", name: "Ренн" },
      { id: "rou", name: "Руан" },
      { id: "sai", name: "Сент-Этьен" },
      { id: "str", name: "Страсбург" },
      { id: "tln", name: "Тулон" },
      { id: "tou", name: "Тулуза" }
    ],
    nl: [
      { id: "alm", name: "Алмере" },
      { id: "ame", name: "Амерсфорт" },
      { id: "ams", name: "Амстердам" },
      { id: "ape", name: "Апелдорн" },
      { id: "arn", name: "Арнем" },
      { id: "bre", name: "Бреда" },
      { id: "gro", name: "Гронинген" },
      { id: "del", name: "Делфт" },
      { id: "dor", name: "Дордрехт" },
      { id: "zaa", name: "Зандам" },
      { id: "zwo", name: "Зволле" },
      { id: "lei", name: "Лейден" },
      { id: "lee", name: "Леуварден" },
      { id: "maa", name: "Маастрихт" },
      { id: "nij", name: "Неймеген" },
      { id: "oss", name: "Осс" },
      { id: "rot", name: "Роттердам" },
      { id: "sit", name: "Ситтард" },
      { id: "til", name: "Тилбург" },
      { id: "utr", name: "Утрехт" },
      { id: "hag", name: "Гаага" },
      { id: "har", name: "Харлем" },
      { id: "hel", name: "Хелмонд" },
      { id: "hen", name: "Хенгело" },
      { id: "ein", name: "Эйндховен" },
      { id: "ens", name: "Энсхеде" }
    ],
    be: [
      { id: "aal", name: "Алст" },
      { id: "ant", name: "Антверпен" },
      { id: "aar", name: "Арлон" },
      { id: "aud", name: "Ауденарде" },
      { id: "bru", name: "Брюссель" },
      { id: "brg", name: "Брюгге" },
      { id: "gen", name: "Генк" },
      { id: "gnt", name: "Гент" },
      { id: "din", name: "Динан" },
      { id: "iep", name: "Ипр" },
      { id: "kor", name: "Кортрейк" },
      { id: "lok", name: "Локерен" },
      { id: "leu", name: "Лёвен" },
      { id: "lie", name: "Льеж" },
      { id: "mec", name: "Мехелен" },
      { id: "mon", name: "Монс" },
      { id: "nam", name: "Намюр" },
      { id: "ost", name: "Остенде" },
      { id: "roe", name: "Рурмонд" },
      { id: "sin", name: "Синт-Никлас" },
      { id: "ton", name: "Тонгерен" },
      { id: "tur", name: "Турне" },
      { id: "has", name: "Хасселт" },
      { id: "cha", name: "Шарлеруа" },
      { id: "euv", name: "Эйпен" }
    ]
  },
  en: {
    de: [
      { id: "ber", name: "Berlin" },
      { id: "ham", name: "Hamburg" },
      { id: "mun", name: "Munich" },
      { id: "col", name: "Cologne" },
      { id: "fra", name: "Frankfurt" },
      { id: "stu", name: "Stuttgart" },
      { id: "dus", name: "Düsseldorf" },
      { id: "dor", name: "Dortmund" },
      { id: "ess", name: "Essen" },
      { id: "lei", name: "Leipzig" },
      { id: "bre", name: "Bremen" },
      { id: "dre", name: "Dresden" },
      { id: "han", name: "Hanover" },
      { id: "nur", name: "Nuremberg" },
      { id: "boc", name: "Bochum" },
      { id: "wup", name: "Wuppertal" },
      { id: "bil", name: "Bielefeld" },
      { id: "bon", name: "Bonn" },
      { id: "man", name: "Mannheim" },
      { id: "kar", name: "Karlsruhe" }
    ],
    fr: [
      { id: "par", name: "Paris" },
      { id: "mar", name: "Marseille" },
      { id: "lyo", name: "Lyon" },
      { id: "tou", name: "Toulouse" },
      { id: "nic", name: "Nice" },
      { id: "nan", name: "Nantes" },
      { id: "str", name: "Strasbourg" },
      { id: "mon", name: "Montpellier" },
      { id: "bor", name: "Bordeaux" },
      { id: "lil", name: "Lille" },
      { id: "ren", name: "Rennes" },
      { id: "rei", name: "Reims" },
      { id: "hav", name: "Le Havre" },
      { id: "sai", name: "Saint-Étienne" },
      { id: "tln", name: "Toulon" },
      { id: "met", name: "Metz" },
      { id: "gre", name: "Grenoble" },
      { id: "dij", name: "Dijon" },
      { id: "ang", name: "Angers" },
      { id: "nim", name: "Nîmes" }
    ],
    nl: [
      { id: "ams", name: "Amsterdam" },
      { id: "rot", name: "Rotterdam" },
      { id: "hag", name: "The Hague" },
      { id: "utr", name: "Utrecht" },
      { id: "ein", name: "Eindhoven" },
      { id: "til", name: "Tilburg" },
      { id: "gro", name: "Groningen" },
      { id: "alm", name: "Almere" },
      { id: "bre", name: "Breda" },
      { id: "nij", name: "Nijmegen" },
      { id: "ens", name: "Enschede" },
      { id: "har", name: "Haarlem" },
      { id: "arn", name: "Arnhem" },
      { id: "zaa", name: "Zaandam" },
      { id: "ame", name: "Amersfoort" }
    ],
    be: [
      { id: "bru", name: "Brussels" },
      { id: "ant", name: "Antwerp" },
      { id: "gnt", name: "Ghent" },
      { id: "lie", name: "Liège" },
      { id: "brg", name: "Bruges" },
      { id: "cha", name: "Charleroi" },
      { id: "nam", name: "Namur" },
      { id: "leu", name: "Leuven" },
      { id: "mon", name: "Mons" },
      { id: "ost", name: "Ostend" },
      { id: "has", name: "Hasselt" },
      { id: "kor", name: "Kortrijk" },
      { id: "sin", name: "Sint-Niklaas" },
      { id: "aud", name: "Oudenaarde" },
      { id: "gen", name: "Genk" }
    ]
  },
  es: {
    de: [
      { id: "ber", name: "Berlín" },
      { id: "ham", name: "Hamburgo" },
      { id: "mun", name: "Múnich" },
      { id: "col", name: "Colonia" },
      { id: "fra", name: "Fráncfort" },
      { id: "stu", name: "Stuttgart" },
      { id: "dus", name: "Düsseldorf" },
      { id: "dor", name: "Dortmund" },
      { id: "ess", name: "Essen" },
      { id: "lei", name: "Leipzig" },
      { id: "bre", name: "Bremen" },
      { id: "dre", name: "Dresde" },
      { id: "han", name: "Hannover" },
      { id: "nur", name: "Núremberg" },
      { id: "boc", name: "Bochum" },
      { id: "wup", name: "Wuppertal" },
      { id: "bil", name: "Bielefeld" },
      { id: "bon", name: "Bonn" },
      { id: "man", name: "Mannheim" },
      { id: "kar", name: "Karlsruhe" }
    ],
    fr: [
      { id: "par", name: "París" },
      { id: "mar", name: "Marsella" },
      { id: "lyo", name: "Lyon" },
      { id: "tou", name: "Toulouse" },
      { id: "nic", name: "Niza" },
      { id: "nan", name: "Nantes" },
      { id: "str", name: "Estrasburgo" },
      { id: "mon", name: "Montpellier" },
      { id: "bor", name: "Burdeos" },
      { id: "lil", name: "Lille" },
      { id: "ren", name: "Rennes" },
      { id: "rei", name: "Reims" },
      { id: "hav", name: "Le Havre" },
      { id: "sai", name: "Saint-Étienne" },
      { id: "tln", name: "Tolón" },
      { id: "met", name: "Metz" },
      { id: "gre", name: "Grenoble" },
      { id: "dij", name: "Dijon" },
      { id: "ang", name: "Angers" },
      { id: "nim", name: "Nimes" }
    ],
    nl: [
      { id: "ams", name: "Ámsterdam" },
      { id: "rot", name: "Róterdam" },
      { id: "hag", name: "La Haya" },
      { id: "utr", name: "Utrecht" },
      { id: "ein", name: "Eindhoven" },
      { id: "til", name: "Tilburg" },
      { id: "gro", name: "Groninga" },
      { id: "alm", name: "Almere" },
      { id: "bre", name: "Breda" },
      { id: "nij", name: "Nimega" },
      { id: "ens", name: "Enschede" },
      { id: "har", name: "Haarlem" },
      { id: "arn", name: "Arnhem" },
      { id: "zaa", name: "Zaandam" },
      { id: "ame", name: "Amersfoort" }
    ],
    be: [
      { id: "bru", name: "Bruselas" },
      { id: "ant", name: "Amberes" },
      { id: "gnt", name: "Gante" },
      { id: "lie", name: "Lieja" },
      { id: "brg", name: "Brujas" },
      { id: "cha", name: "Charleroi" },
      { id: "nam", name: "Namur" },
      { id: "leu", name: "Lovaina" },
      { id: "mon", name: "Mons" },
      { id: "ost", name: "Ostende" },
      { id: "has", name: "Hasselt" },
      { id: "kor", name: "Cortrique" },
      { id: "sin", name: "Sint-Niklaas" },
      { id: "aud", name: "Oudenaarde" },
      { id: "gen", name: "Genk" }
    ]
  }
};
