// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drzlexcajbtcjazclxac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyemxleGNhamJ0Y2phemNseGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NTIwMTAsImV4cCI6MjA1NTIyODAxMH0.V8eP9BcC4pmZel9OGaZ3epe8B5CXEWdcky31qhGdbVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);